defaults : &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development: &DEV
  <<: *defaults
  database: twitguru_development

test: &TEST
  <<: *defaults
  database: twitguru_test
